name: Publish to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 6-22.04
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v49.0.2
    permissions:
      contents: read
      actions: read

  release:
    name: Release rock
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_rock_edge.yaml@v49.0.2
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    permissions:
      packages: write  # Needed to publish to GitHub Container Registry
      contents: write  # Needed to create git tags
      actions: write  # Needed to create git workflows